create sequence superandes_sequence  ;

-- Tabla Sucursales
CREATE TABLE sucursales (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255 BYTE),
    telefono VARCHAR2(50 BYTE),
    direccion VARCHAR2(255 BYTE),
    tamano NUMBER,
    id_ciudad NUMBER,
    CONSTRAINT fk_sucursales_ciudad FOREIGN KEY (id_ciudad) REFERENCES ciudades(id)
);

-- Tabla Ciudades
CREATE TABLE ciudades (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo NUMBER NOT NULL,
    nombre VARCHAR2(255 BYTE) NOT NULL
);

-- Tabla Proveedores
CREATE TABLE proveedores (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NIT VARCHAR2(50 BYTE),
    direccion VARCHAR2(255 BYTE),
    nombrePersonaC VARCHAR2(255 BYTE),
    telefonoPersonaC VARCHAR2(50 BYTE)
);

-- Tabla Categor�as
CREATE TABLE categorias (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo NUMBER NOT NULL,
    nombre VARCHAR2(255 BYTE) NOT NULL,
    descripcion VARCHAR2(500 BYTE),
    caracteristicasAlmacenamiento VARCHAR2(500 BYTE)
);

-- Tabla Bodegas
CREATE TABLE bodegas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255 BYTE) NOT NULL,
    tamano NUMBER,
    id_sucursal NUMBER,
    CONSTRAINT fk_bodega_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursales(id)
);

-- Tabla Clientes
CREATE TABLE clientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula NUMBER NOT NULL,
    nombre VARCHAR2(255 BYTE) NOT NULL
);

-- Tabla Productos
CREATE TABLE productos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigoBarras VARCHAR2(255 BYTE) NOT NULL,
    nombre VARCHAR2(255 BYTE),
    costoBodega NUMBER,
    precioVenta NUMBER,
    presentacion VARCHAR2(255 BYTE),
    cantidadPresentacion NUMBER,
    unidadMedida NUMBER(1),
    volumenEmpaque NUMBER,
    pesoEmpaque NUMBER,
    fechaExpiracion DATE,
    id_categoria NUMBER,
    CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES categorias(id)
);

-- Tabla InfoRecepcion (con PK compuesta)
CREATE TABLE info_recepcion (
    id_recepcion NUMBER,
    id_producto NUMBER,
    cantidadRecibida NUMBER,
    costoRecibido NUMBER,
    CONSTRAINT pk_info_recepcion PRIMARY KEY (id_recepcion, id_producto),
    CONSTRAINT fk_info_recepcion_producto FOREIGN KEY (id_producto) REFERENCES productos(id),
    CONSTRAINT fk_info_recepcion_recepcion FOREIGN KEY (id_recepcion) REFERENCES recepciones(id)
);

-- Tabla Recepciones
CREATE TABLE recepciones (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaRecepcion DATE,
    id_proveedor NUMBER,
    id_bodega NUMBER,
    CONSTRAINT fk_recepcion_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedores(id),
    CONSTRAINT fk_recepcion_bodega FOREIGN KEY (id_bodega) REFERENCES bodegas(id)
);

-- Tabla Niveles de Reorden
CREATE TABLE niveles_reorden (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nivelMinimo NUMBER,
    id_sucursal NUMBER,
    id_producto NUMBER,
    CONSTRAINT fk_nivel_reorden_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursales(id),
    CONSTRAINT fk_nivel_reorden_producto FOREIGN KEY (id_producto) REFERENCES productos(id)
);

-- Tabla Ordenes de Compra
CREATE TABLE ordenes_compra (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaEsperadaEntrega DATE,
    precioAcordado NUMBER,
    estado VARCHAR2(50 BYTE),
    fechaCreacion DATE,
    id_sucursal NUMBER,
    id_proveedor NUMBER,
    CONSTRAINT fk_orden_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursales(id),
    CONSTRAINT fk_orden_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedores(id)
);

-- Tabla ProductoBodega (con PK compuesta)
CREATE TABLE producto_bodega (
    id_producto NUMBER,
    id_bodega NUMBER,
    cantidadExistente NUMBER,
    costoPromedio NUMBER,
    capacidadBodega NUMBER,
    CONSTRAINT pk_producto_bodega PRIMARY KEY (id_producto, id_bodega),
    CONSTRAINT fk_producto_bodega_producto FOREIGN KEY (id_producto) REFERENCES productos(id),
    CONSTRAINT fk_producto_bodega_bodega FOREIGN KEY (id_bodega) REFERENCES bodegas(id)
);

-- Tabla ProductoOrden (con PK compuesta)
CREATE TABLE producto_orden (
    id_producto NUMBER,
    id_ordenCompra NUMBER,
    precioAcordado NUMBER,
    cantidadSolicitada NUMBER,
    CONSTRAINT pk_producto_orden PRIMARY KEY (id_producto, id_ordenCompra),
    CONSTRAINT fk_producto_orden_producto FOREIGN KEY (id_producto) REFERENCES PRODUCTOS(id),
    CONSTRAINT fk_producto_orden_orden FOREIGN KEY (id_ordenCompra) REFERENCES ORDENES_COMPRA(id)
);

-- Tabla Ventas
CREATE TABLE ventas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE,
    cantidad NUMBER,
    precioUnitario NUMBER,
    cedula NUMBER,
    id_cliente NUMBER,
    id_producto NUMBER,
    CONSTRAINT fk_venta_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id),
    CONSTRAINT fk_venta_producto FOREIGN KEY (id_producto) REFERENCES productos(id)
);