create sequence superandes_sequence  ;

-- Tabla Ciudades
CREATE TABLE ciudades (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo NUMBER NOT NULL,
    nombre VARCHAR2(255 BYTE) NOT NULL
);

-- Tabla Sucursales
CREATE TABLE sucursales (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255 BYTE),
    telefono VARCHAR2(50 BYTE),
    direccion VARCHAR2(255 BYTE),
    tamano NUMBER,
    ciudad_id NUMBER,
    CONSTRAINT fk_sucursales_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudades(id)
);


-- Tabla Proveedores
CREATE TABLE proveedores (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NIT VARCHAR2(50 BYTE),
    direccion VARCHAR2(255 BYTE),
    nombre_personac VARCHAR2(255 BYTE),
    telefono_personac VARCHAR2(50 BYTE)
);

-- Tabla Categorías
CREATE TABLE categorias (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo NUMBER NOT NULL,
    nombre VARCHAR2(255 BYTE) NOT NULL,
    descripcion VARCHAR2(500 BYTE),
    caracteristicas_almacenamiento VARCHAR2(500 BYTE)
);

-- Tabla Bodegas
CREATE TABLE bodegas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255 BYTE) NOT NULL,
    tamano NUMBER,
    sucursal_id NUMBER,
    CONSTRAINT fk_bodega_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursales(id)
);

-- Tabla Clientes
CREATE TABLE clientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula NUMBER NOT NULL,
    nombre VARCHAR2(255 BYTE) NOT NULL
);

-- Tabla Productos
CREATE TABLE productos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_barras VARCHAR2(255 BYTE) NOT NULL,
    nombre VARCHAR2(255 BYTE),
    costo_bodega NUMBER,
    precio_venta NUMBER,
    presentacion VARCHAR2(255 BYTE),
    cantidad_presentacion NUMBER,
    unidad_medida NUMBER(1),
    volumen_empaque NUMBER,
    peso_empaque NUMBER,
    fecha_expiracion DATE,
    categoria_id NUMBER,
    CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id)
);


-- Tabla Recepciones
CREATE TABLE recepciones (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_recepcion DATE,
    proveedor_id NUMBER,
    bodega_id NUMBER,
    CONSTRAINT fk_recepcion_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores(id),
    CONSTRAINT fk_recepcion_bodega FOREIGN KEY (bodega_id) REFERENCES bodegas(id)
);

-- Tabla InfoRecepcion (con PK compuesta)
CREATE TABLE info_recepcion (
    recepcion_id NUMBER,
    producto_id NUMBER,
    cantidad_recibida NUMBER,
    costo_recibido NUMBER,
    CONSTRAINT pk_info_recepcion PRIMARY KEY (recepcion_id, producto_id),
    CONSTRAINT fk_info_recepcion_producto FOREIGN KEY (producto_id) REFERENCES productos(id),
    CONSTRAINT fk_info_recepcion_recepcion FOREIGN KEY (recepcion_id) REFERENCES recepciones(id)
);


-- Tabla Niveles de Reorden
CREATE TABLE niveles_reorden (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nivel_minimo NUMBER,
    sucursal_id NUMBER,
    producto_id NUMBER,
    CONSTRAINT fk_nivel_reorden_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursales(id),
    CONSTRAINT fk_nivel_reorden_producto FOREIGN KEY (producto_id) REFERENCES productos(id)
);

-- Tabla Ordenes de Compra
CREATE TABLE ordenes_compra (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaEsperadaEntrega DATE,
    precio_acordado NUMBER,
    estado VARCHAR2(50 BYTE),
    fechaCreacion DATE,
    sucursal_id NUMBER,
    proveedor_id NUMBER,
    CONSTRAINT fk_orden_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursales(id),
    CONSTRAINT fk_orden_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores(id)
);

-- Tabla ProductoBodega (con PK compuesta)
CREATE TABLE producto_bodega (
    producto_id NUMBER,
    bodega_id NUMBER,
    cantidad_existente NUMBER,
    costo_promedio NUMBER,
    capacidad_bodega NUMBER,
    CONSTRAINT pk_producto_bodega PRIMARY KEY (producto_id, bodega_id),
    CONSTRAINT fk_producto_bodega_producto FOREIGN KEY (producto_id) REFERENCES productos(id),
    CONSTRAINT fk_producto_bodega_bodega FOREIGN KEY (bodega_id) REFERENCES bodegas(id)
);

-- Tabla ProductoOrden (con PK compuesta)
CREATE TABLE producto_orden (
    producto_id NUMBER,
    orden_compra_id NUMBER,
    precio_acordado NUMBER,
    cantidad_solicitada NUMBER,
    CONSTRAINT pk_producto_orden PRIMARY KEY (producto_id, orden_compra_id),
    CONSTRAINT fk_producto_orden_producto FOREIGN KEY (producto_id) REFERENCES PRODUCTOS(id),
    CONSTRAINT fk_producto_orden_orden FOREIGN KEY (orden_compra_id) REFERENCES ORDENES_COMPRA(id)
);

-- Tabla Ventas
CREATE TABLE ventas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE,
    cantidad NUMBER,
    precio_unitario NUMBER,
    cedula NUMBER,
    cliente_id NUMBER,
    producto_id NUMBER,
    CONSTRAINT fk_venta_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_venta_producto FOREIGN KEY (producto_id) REFERENCES productos(id)
);